### ISSUE TITLE
replaceDirnamePlugin will crash while string includes import.meta.url

### ISSUE THREAD

**Issue by lvqq** [egoist/bundle-require#32]
I find bundle-require uses a custom esbuild plugin to handle path, source code is:
```typescript
export const replaceDirnamePlugin = (): EsbuildPlugin => {
  return {
    name: "bundle-require:replace-path",
    setup(ctx) {
      ctx.onLoad({ filter: JS_EXT_RE }, async (args) => {
        const contents = await fs.promises.readFile(args.path, "utf-8")
        return {
          contents: contents
            .replace(/[^"'\\]\b__filename\b[^"'\\]/g, (match) =>
              match.replace("__filename", JSON.stringify(args.path)),
            )
            .replace(/[^"'\\]\b__dirname\b[^"'\\]/g, (match) =>
              match.replace(
                "__dirname",
                JSON.stringify(path.dirname(args.path)),
              ),
            )
            .replace(/[^"'\\]\bimport\.meta\.url\b[^"'\\]/g, (match) =>
              match.replace(
                "import.meta.url",
                JSON.stringify(`file://${args.path}`),
              ),
            ),
          loader: inferLoader(path.extname(args.path)),
        }
      })
    },
  }
}
```

Here has a problem while a string including keywords like `__filename`, `__dirname` or `import.meta.data`, the path in string is handled too. See the example in `tsup.config.ts` using `banner`: https://github.com/egoist/tsup/issues/719.

So maybe we need to add logic to exclude path in string. But regexp match seems hard to judge if the path reference is in string or not. Is there any quick way to fix this problem? AST may do, but it complicates the logic of the plugin.

**Comment by egoist** [comment]
figured out a way to do this using esbuild's `define` option and inject some code by peeking Vite's source code: https://github.com/vitejs/vite/blob/51ed05915ae1fcebacd5bcebca76559a2b8e4473/packages/vite/src/node/config.ts#L1013
