### ISSUE TITLE
Imports not working with Vitest

### ISSUE THREAD

**Issue by innocenzi** [egoist/bundle-require#6]
I'm using `bundle-require` in a project, and by default, tests with Vitest fail: 

![](https://i.imgur.com/BATtSWz.png)

Using `esno` to run the same code works: 

![](https://i.imgur.com/u6bZATk.png)

I also discovered that overriding `require` to use `import` could make it work: 

```ts
const result = await bundleRequire({ 
	filepath,
	require: (id: string) => import(id)
})
```

I'm not familiar with how CJS/ESM work exactly, so I'm unsure if it is a viable workaround or not. 

Here is a repository where you can reproduce the issue: https://github.com/innocenzi/vitest-bundle-require-reproduction

Run `pnpm test` to see the failing test.
Run `pnpm cli` to see the working CLI call.

I'm thinking https://github.com/egoist/bundle-require/blob/main/src/utils.ts#L53 could be tweaked to make it work with Vitest, the same way it is for Jest?

**Comment by egoist** [comment]
weird, your repo works for me:

<img width="839" alt="CleanShot 2022-01-01 at 13 09 56@2x" src="https://user-images.githubusercontent.com/8784712/147844385-fb9819b2-270b-4238-9387-108826ddb25f.png">

**Comment by innocenzi** [comment]
Definitely not working for me. 

![](https://i.imgur.com/WSjWfV7.png)

I'm on Windows 10, node v16.13.1, and the versions are locked by the lockfile. Any clue what would make the difference?

**Comment by egoist** [comment]
3.0 should work with Vitest

**Comment by innocenzi** [comment]
I have since changed my approach so I can't confirm if this works. :/ 

I'll close the issue so if someone have trouble with that they can create a more specific one. Thanks for your work <3
